[package]
name = "yarr-tracer"
version = "0.1.0"
edition = "2021"

[dependencies]
exmex = { version = "0.20.4", features = ["value"] }
image = "0.25.8"
kdl = "6.3.4"
num_cpus = "1.17.0"
rand = "0.9.2"
smallvec = "1.15.1"
